package com.meditation.backend.sync;

import java.util.List;

// Generated by scripts/generate-sync-contract.mjs. Do not edit manually.
public final class GeneratedSyncContract {

  public static final int SCHEMA_VERSION = 1;
  public static final String SYNC_QUEUED_AT_HEADER = "X-Meditation-Sync-Queued-At";
  public static final String SYNC_RESULT_HEADER = "X-Meditation-Sync-Result";
  public static final String SYNC_OUTCOME_APPLIED = "applied";
  public static final String SYNC_OUTCOME_STALE = "stale";
  public static final String SYNC_OUTCOME_DELETED = "deleted";
  public static final String DELETE_CURRENT_RECORD_FIELD = "currentRecord";
  public static final String DELETE_CUSTOM_PLAY_ALIAS_FIELD = "currentCustomPlay";
  public static final String DELETE_PLAYLIST_ALIAS_FIELD = "currentPlaylist";
  public static final String DELETE_SANKALPA_ALIAS_FIELD = "currentSankalpa";
  public static final List<String> MEDITATION_TYPES = List.of("Vipassana", "Ajapa", "Tratak", "Kriya", "Sahaj");
  public static final List<String> SESSION_LOG_SOURCES = List.of("auto log", "manual log");
  public static final List<String> TIME_OF_DAY_BUCKETS = List.of("morning", "afternoon", "evening", "night");
  public static final List<String> GOAL_TYPES = List.of("duration-based", "session-count-based", "observance-based");
  public static final List<String> OBSERVANCE_STATUSES = List.of("observed", "missed");
  public static final List<String> TIMER_MODES = List.of("fixed", "open-ended");
  public static final List<String> SESSION_LOG_STATUSES = List.of("completed", "ended early");

  private GeneratedSyncContract() {
  }
}
