create table meditation_type_ref (
  code varchar(32) primary key,
  display_name varchar(64) not null,
  sort_order integer not null,
  active boolean not null default true,
  created_at timestamp with time zone not null default current_timestamp
);

create unique index ux_meditation_type_ref_sort_order on meditation_type_ref (sort_order);

create table media_asset (
  id varchar(64) primary key,
  asset_kind varchar(32) not null,
  label varchar(160) not null,
  meditation_type_code varchar(32),
  relative_path varchar(255) not null,
  duration_seconds integer not null,
  mime_type varchar(100) not null,
  size_bytes bigint not null,
  active boolean not null default true,
  updated_at timestamp with time zone not null,
  constraint fk_media_asset_meditation_type
    foreign key (meditation_type_code) references meditation_type_ref (code),
  constraint chk_media_asset_duration
    check (duration_seconds >= 0),
  constraint chk_media_asset_size
    check (size_bytes >= 0)
);

create index ix_media_asset_kind_active on media_asset (asset_kind, active);

create table custom_play (
  id varchar(64) primary key,
  title varchar(160) not null,
  meditation_type_code varchar(32) not null,
  duration_minutes integer not null,
  media_asset_id varchar(64),
  favorite boolean not null default false,
  notes varchar(500),
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint fk_custom_play_meditation_type
    foreign key (meditation_type_code) references meditation_type_ref (code),
  constraint fk_custom_play_media_asset
    foreign key (media_asset_id) references media_asset (id),
  constraint chk_custom_play_duration
    check (duration_minutes > 0)
);

create table playlist (
  id varchar(64) primary key,
  name varchar(160) not null,
  favorite boolean not null default false,
  small_gap_seconds integer not null default 0,
  created_at timestamp with time zone not null,
  updated_at timestamp with time zone not null,
  constraint chk_playlist_small_gap
    check (small_gap_seconds >= 0)
);

create table playlist_item (
  id bigint generated by default as identity primary key,
  playlist_id varchar(64) not null,
  position_index integer not null,
  meditation_type_code varchar(32) not null,
  title varchar(160) not null,
  duration_minutes integer not null,
  custom_play_id varchar(64),
  created_at timestamp with time zone not null default current_timestamp,
  constraint fk_playlist_item_playlist
    foreign key (playlist_id) references playlist (id) on delete cascade,
  constraint fk_playlist_item_meditation_type
    foreign key (meditation_type_code) references meditation_type_ref (code),
  constraint fk_playlist_item_custom_play
    foreign key (custom_play_id) references custom_play (id),
  constraint chk_playlist_item_duration
    check (duration_minutes > 0)
);

create unique index ux_playlist_item_playlist_position
  on playlist_item (playlist_id, position_index);

create table sankalpa_goal (
  id varchar(64) primary key,
  goal_type varchar(32) not null,
  target_value integer not null,
  days integer not null,
  meditation_type_code varchar(32),
  time_of_day_bucket varchar(32),
  created_at timestamp with time zone not null,
  completed_at timestamp with time zone,
  archived boolean not null default false,
  constraint fk_sankalpa_goal_meditation_type
    foreign key (meditation_type_code) references meditation_type_ref (code),
  constraint chk_sankalpa_goal_target_value
    check (target_value > 0),
  constraint chk_sankalpa_goal_days
    check (days > 0)
);

create table session_log (
  id varchar(64) primary key,
  source varchar(32) not null,
  status varchar(32) not null,
  meditation_type_code varchar(32) not null,
  started_at timestamp with time zone not null,
  ended_at timestamp with time zone not null,
  planned_duration_seconds integer,
  completed_duration_seconds integer not null,
  custom_play_id varchar(64),
  playlist_id varchar(64),
  playlist_item_position integer,
  playlist_item_count integer,
  playlist_run_id varchar(64),
  playlist_run_started_at timestamp with time zone,
  notes varchar(500),
  created_at timestamp with time zone not null,
  constraint fk_session_log_meditation_type
    foreign key (meditation_type_code) references meditation_type_ref (code),
  constraint fk_session_log_custom_play
    foreign key (custom_play_id) references custom_play (id),
  constraint fk_session_log_playlist
    foreign key (playlist_id) references playlist (id),
  constraint chk_session_log_completed_duration
    check (completed_duration_seconds >= 0),
  constraint chk_session_log_planned_duration
    check (planned_duration_seconds is null or planned_duration_seconds >= 0),
  constraint chk_session_log_time_order
    check (ended_at >= started_at)
);

create index ix_session_log_ended_at on session_log (ended_at);
