import Foundation

// Generated by scripts/generate-sync-contract.mjs. Do not edit manually.
public enum GeneratedSyncContract {
    public static let schemaVersion = 1
    public static let syncQueuedAtHeader = "X-Meditation-Sync-Queued-At"
    public static let syncResultHeader = "X-Meditation-Sync-Result"
    public static let syncOutcomeApplied = "applied"
    public static let syncOutcomeStale = "stale"
    public static let syncOutcomeDeleted = "deleted"
    public static let deleteCurrentRecordField = "currentRecord"
    public static let deleteLegacyAliasFields: [String: String] = [
        "customPlay": "currentCustomPlay",
        "playlist": "currentPlaylist",
        "sankalpa": "currentSankalpa",
    ]
    public static let meditationTypes = ["Vipassana", "Ajapa", "Tratak", "Kriya", "Sahaj"]
    public static let sessionLogSources = ["auto log", "manual log"]
    public static let timeOfDayBuckets = ["morning", "afternoon", "evening", "night"]
    public static let goalTypes = ["duration-based", "session-count-based", "observance-based"]
    public static let observanceStatuses = ["observed", "missed"]
    public static let timerModes = ["fixed", "open-ended"]
    public static let sessionLogStatuses = ["completed", "ended early"]
}
